import XCTest

/// Captures the six App Store frames from the running app.
///
/// The whole point of this file is that the store listing shows NEXT rendering, not a
/// reproduction of NEXT. Every earlier mockup was CSS built from `NextPalette` and `NextType`;
/// accurate about colour and metrics and still a drawing. These are the app.
///
/// **Skipped unless `CAPTURE_SCREENSHOTS=1`.** It is in the ordinary UI target so it compiles and
/// stays honest with every other test, but capturing takes minutes and produces no assertion
/// anybody needs on a normal run, so CI drives it in a step of its own.
///
/// Frames, in the order the listing tells them (D-024):
///
/// 1. Capture, mid-dump          4. Focus, running
/// 2. Today, recommending        5. Rescue, four ways of being stuck
/// 3. Why this?                  6. Today on overdue work, dark appearance
///
/// Only the *data* is seeded — see `NEXTApp.seedArgument`. Nothing about the interface is staged.
final class ScreenshotCaptureUITests: XCTestCase {

    /// The 6.7-inch portrait frame the App Store expects.
    private let expectedSize = CGSize(width: 1290, height: 2796)

    override func setUpWithError() throws {
        try super.setUpWithError()
        continueAfterFailure = false
        try XCTSkipUnless(
            ProcessInfo.processInfo.environment["CAPTURE_SCREENSHOTS"] == "1",
            "Set CAPTURE_SCREENSHOTS=1 to capture the App Store set."
        )
    }

    override func tearDown() {
        XCUIDevice.shared.appearance = .light
        super.tearDown()
    }

    // MARK: Capturing

    /// Saves the screen under a name the compositing step can find.
    ///
    /// `.keepAlways`, because the default lifetime deletes attachments for passing tests — and
    /// every one of these passes, so the default would throw away the entire deliverable.
    private func capture(_ app: XCUIApplication, _ name: String) {
        let shot = XCUIScreen.main.screenshot()
        let attachment = XCTAttachment(screenshot: shot)
        attachment.name = name
        attachment.lifetime = .keepAlways
        add(attachment)

        // Recorded rather than asserted. A runner whose only iPhone is the wrong size should
        // still hand back usable frames plus a loud note about what they actually are, instead
        // of failing and producing nothing.
        let size = shot.image.size
        let scale = shot.image.scale
        let pixels = CGSize(width: size.width * scale, height: size.height * scale)
        if pixels != expectedSize {
            XCTContext.runActivity(named: "\(name): captured \(Int(pixels.width))x\(Int(pixels.height)), expected 1290x2796") { _ in }
        }
    }

    private func launch(_ extraArguments: [String] = []) -> XCUIApplication {
        let app = XCUIApplication()
        app.launchArguments = ["-ui-testing"] + extraArguments
        app.launch()

        let skip = app.buttons["onboarding-skip-button"]
        XCTAssertTrue(skip.waitForExistence(timeout: 15))
        let hittable = XCTNSPredicateExpectation(
            predicate: NSPredicate(format: "isHittable == true"), object: skip
        )
        XCTAssertEqual(XCTWaiter().wait(for: [hittable], timeout: 15), .completed)
        skip.tap()
        return app
    }

    /// Waits for the screen to settle before the shutter. Without it the card's one animated
    /// moment is caught mid-transition, which is exactly the frame nobody wants.
    private func settle() {
        _ = XCTWaiter().wait(for: [XCTestExpectation(description: "settle")], timeout: 0.9)
    }

    // MARK: The six frames

    func testCaptureTheAppStoreSet() throws {
        // 1 — Capture, mid-dump.
        var app = launch()
        app.buttons["empty-add-button"].tap()
        let field = app.textFields["capture-text-field"]
        XCTAssertTrue(field.waitForExistence(timeout: 8))
        field.tap()
        field.typeText("Chem test monday, finish history slides friday, email professor about the extension, reading for seminar")
        settle()
        capture(app, "01-capture")

        // 2 — Today, recommending. Seeded so the card carries a deadline and an estimate; typing
        // the same task through Capture would leave both empty and show less of the product.
        app = launch(["-ui-seed", "essay"])
        XCTAssertTrue(app.buttons["start-button"].waitForExistence(timeout: 12))
        settle()
        capture(app, "02-today")

        // 3 — Why this? The real explanation, generated by the engine rather than written here.
        app.buttons["why-this-button"].tap()
        XCTAssertTrue(app.staticTexts["Why this?"].waitForExistence(timeout: 6))
        settle()
        capture(app, "03-why")

        // 4 — Focus, running.
        app.buttons["OK"].tap()
        XCTAssertTrue(app.buttons["start-button"].waitForExistence(timeout: 6))
        app.buttons["start-button"].tap()
        let justStart = app.buttons["focus-start-button"]
        XCTAssertTrue(justStart.waitForExistence(timeout: 8))
        app.buttons["focus-timer-25"].tap()
        XCTAssertTrue(app.buttons["focus-done-button"].waitForExistence(timeout: 8))
        settle()
        capture(app, "04-focus")

        // 5 — Rescue.
        app.buttons["focus-im-stuck-button"].tap()
        XCTAssertTrue(app.buttons["rescue-path-tooMuch"].waitForExistence(timeout: 8))
        settle()
        capture(app, "05-stuck")

        // 6 — Overdue, in the dark appearance. The one frame of the six that is dark, and the
        // reason `testTheCardScreensPassTheAuditInDarkMode` exists: the listing may not claim an
        // appearance the audit has never seen.
        XCUIDevice.shared.appearance = .dark
        app = launch(["-ui-seed", "overdue"])
        XCTAssertTrue(app.buttons["start-button"].waitForExistence(timeout: 12))
        settle()
        capture(app, "06-late")
    }
}
